### ISSUE TITLE
Service - Query from FoodCentral API

### ISSUE THREAD

**Issue by jsyllu** [jsyllu/vital-android#3]

**Comment by 0zz10** [comment]
Test CRUD operations at [Database API](https://fdc.nal.usda.gov/fdc-app.html#/):

Only Foundation Foods will be filtered after the query response returns.

Resources:
https://fdc.nal.usda.gov/api-guide.html
https://fdc.nal.usda.gov/docs/Foundation_Foods_Documentation_Apr2021.pdf

**Comment by 0zz10** [comment]
https://fdc.nal.usda.gov/api-spec/fdc_api.html#/FDC/getFood
API Guidances
- Try in Postman
