### ISSUE TITLE
ShakyShaky Feature - Using Accelerometer 

### ISSUE THREAD

**Issue by jsyllu** [jsyllu/vital-android#4]

**Comment by 0zz10** [comment]
Resources:
https://demonuts.com/android-shake-detection/
https://jasonmcreynolds.com/?p=388
https://www.tutorialspoint.com/how-to-detect-shake-event-in-android-app
https://stackoverflow.com/questions/5271448/how-to-detect-shake-event-with-android

**Comment by 0zz10** [comment]
https://www.youtube.com/watch?v=zUzZ67grYt8
https://www.youtube.com/watch?v=fPa9Sev7il8

**Comment by 0zz10** [comment]
SensorManager lets you access the device's sensors.
https://developer.android.com/reference/android/hardware/SensorManager
